### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by cammac60**
- This PR changes our `readme.md` file and adds an overview, how to use, setup, known issues, and contributors sections. 

---------------

- I am planning to add screenshots in several sections but I will do so manually once this is merged so that I can upload directly to GH.

### CODE REVIEW

**Comment by cammac60** [comment]
The commits prior to `Add overview` are just merge conflict fixes that are in my master branch that I haven't been able to remove. I think they have already been merged so they shouldn't change anything but feel free to pull down the branch if you'd like to double check.

**Comment by trishalanglois** [comment]
The changes look good, @cammac60!  

@allisonjw, she's ready for your eyes and to merge.

Nice work, team!

**Comment by cammac60** [comment]
@trishalanglois Thanks! And I'll be adding a few screenshots once it's merged.

**Comment by allisonjw** [comment]
@cammac60 Thank for taking the time to prepare this for the app. We will want to add a brief description/1-line description at the top of the repo too. Well done team!

**Pull request merged**
