### PR TITLE
Alt tags for images

### PR DESCRIPTION
**Pull request by trishalanglois**
#### What's this PR do?
Adds alt tags to all images with a brief description of what the image is.  This way, if a user is using a screen reader, the screen reader is able to provide the listed description of the image.
#### Where should the reviewer start?
Look through the index.html file, and do a cmd + f, locating all  tags.  From there, you can see the "alt" descriptions for each one.
#### How should this be manually tested?
You can run an ARIA tester to see the accessibility score increase because of the presence of alt tags.
#### Any background context you want to provide?
It's going to be important to include alt tags for any images that we have.  If we add any more images during this project, we'll want to make sure we're also including alt tags on those pictures, too.
#### What are the relevant tickets?
This PR would close issue #17 
#### Screenshots (if appropriate)
N/A
#### Questions:
Please let me know if you see any other images that we should put an alt tag on!  I looked through the things being appended to the DOM through innerHTML, but there are no additional images we are adding.
Do either of you know how a screen reader interacts with charts?  I don't think there's an alt tag on them to provide additional descriptions, but there may be an equivalent we should add.

### CODE REVIEW

**Comment by allisonjw** [comment]
@trishalanglois 
Great job with Alt text. They give the intent, purpose, and meaning of the image to the reader. 

For the canvas element, I found the following article regarding text. Essentially, we need to add something like this into all the canvas elements were the graphs are rendered (role="img" aria-label="Bar Chart Showing a Single User's Step Count For Everyday of a Week")

http://pauljadam.com/demos/canvas.html

**Comment by cammac60** [comment]
@trishalanglois Same as my comment on your other PR, can you please fix the merge conflicts on this and let me know if the added lines on `package-lock.json` will cause any issues? 

Other than that, this looks great! Your alt tags provide the perfect amount of context.

**Comment by trishalanglois** [comment]
> @trishalanglois Same as my comment on your other PR, can you please fix the merge conflicts on this and let me know if the added lines on `package-lock.json` will cause any issues?
> 
> Other than that, this looks great! Your alt tags provide the perfect amount of context.

**Comment by trishalanglois** [comment]
Oops, didn't mean to close this!

Okay, branch has been updated to include label tags for all the charts.

**Comment by allisonjw** [comment]
Fantastic. Well done on improving our accessibility. With these additions we are on our way to being the goal of 100%!

**Pull request merged**
